### ISSUE TITLE
Help: Legacy chat formatting

### ISSUE THREAD

**Issue by TymekSL** [Matt-MX/DisplayNameTags#24]
```[23:19:41 WARN]: [NameTags] Async task for NameTags v1.1-commit-ee07cbb generated an exception
java.lang.NullPointerException: Cannot invoke "com.mattmx.nametags.entity.NameTagEntity.getMeta()" because "entity" is null
        at DisplayNameTags-1.1.jar/com.mattmx.nametags.config.ConfigDefaultsListener.lambda$onCreate$3(ConfigDefaultsListener.java:42) ~[DisplayNameTags-1.1.jar:?]
        at DisplayNameTags-1.1.jar/com.mattmx.nametags.entity.trait.RefreshTrait.lambda$new$0(RefreshTrait.java:21) ~[DisplayNameTags-1.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:19:41 INFO]: Player BloodyMonkey383 joined. Playtime tracking started.```

**Comment by Matt-MX** [comment]
Hey is it possible you can provide the full logs via a pastebin or something?

**Comment by TymekSL** [comment]
Im not using folia,paperspigot

**Comment by Matt-MX** [comment]
> Im not using folia,paperspigot

Okay awesome, can you please provide full logs as I cannot reproduce this. Also please use the latest development build here:
https://github.com/Matt-MX/DisplayNameTags/actions/runs/11800575123/job/32871804015

**Comment by TymonLC** [comment]
didn't saw this again, i will make again post when i saw this again ok?
