### ISSUE TITLE
Help: Legacy text formatter

### ISSUE THREAD

**Issue by TymekSL** [Matt-MX/DisplayNameTags#30]
Using tlauncher on the second account and feather client on the main account. 
And: 
X - Premium acccount 
Y - second account

I see the Y tag on the X account 
but dont see the X on the tlauncher Y account 
I have permissions, for the tag so i dont know whats happenned here, could you help me ? 
1.21.2
```
[01:00:30 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        <red>§6leos</red>
             ^^
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[adventure-text-minimessage-4.17.0.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextFormatter.lambda$static$0(TextFormatter.java:15) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextFormatter.format(TextFormatter.java:42) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.convertToComponent(TextDisplayMetaConfiguration.java:183) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.lambda$applyTextMeta$0(TextDisplayMetaConfiguration.java:27) ~[DisplayNameTags-1.3.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.applyTextMeta(TextDisplayMetaConfiguration.java:35) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:69) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:00:30 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        <red>§6leos</red>
             ^^
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[adventure-text-minimessage-4.17.0.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextFormatter.lambda$static$0(TextFormatter.java:15) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextFormatter.format(TextFormatter.java:42) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.convertToComponent(TextDisplayMetaConfiguration.java:183) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.lambda$applyTextMeta$0(TextDisplayMetaConfiguration.java:27) ~[DisplayNameTags-1.3.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.applyTextMeta(TextDisplayMetaConfiguration.java:35) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:69) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:00:30 INFO]: BloodyMonkey383 lost connection: Disconnected
[01:00:30 INFO]: Player BloodyMonkey383 left. Playtime data saved.
[01:00:30 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        <red>§6leos</red>
             ^^
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[adventure-text-minimessage-4.17.0.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextFormatter.lambda$static$0(TextFormatter.java:15) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextFormatter.format(TextFormatter.java:42) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.convertToComponent(TextDisplayMetaConfiguration.java:183) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.lambda$applyTextMeta$0(TextDisplayMetaConfiguration.java:27) ~[DisplayNameTags-1.3.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.applyTextMeta(TextDisplayMetaConfiguration.java:35) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:69) ~[DisplayNameTags-1.3.jar:?]
        at DisplayNameTags-1.3.jar/com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:01:43 INFO]: [TokenStatUpdater] Updated Token-Stats!
```

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the TextFormatter enum to handle legacy formatting codes when using MiniMessage formatter. This should resolve the issue with legacy codes causing exceptions.

You can review changes in this commit: https://github.com/lattaai13/Matt-MX-DisplayNameTags-30/commit/f4efb8bb1e1f5884fac21a78fc83aadee8f1f162.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by TymekSL** [comment]
> Hello, I tried to solve the issue.
> 
> This is what I did:
> 
> Modified the TextFormatter enum to handle legacy formatting codes when using MiniMessage formatter. This should resolve the issue with legacy codes causing exceptions.
> 
> You can review changes in this commit: [lattaai13@f4efb8b](https://github.com/lattaai13/Matt-MX-DisplayNameTags-30/commit/f4efb8bb1e1f5884fac21a78fc83aadee8f1f162).
> 
> Caution
> 
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission
> 
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

can't make this as jar? as beta version? lol i totally dont understand what you wrote, ok thanks you resolved the issue but i dont see the jar

**Comment by Matt-MX** [comment]
> > Hello, I tried to solve the issue.
> > This is what I did:
> > Modified the TextFormatter enum to handle legacy formatting codes when using MiniMessage formatter. This should resolve the issue with legacy codes causing exceptions.
> > You can review changes in this commit: [lattaai13@f4efb8b](https://github.com/lattaai13/Matt-MX-DisplayNameTags-30/commit/f4efb8bb1e1f5884fac21a78fc83aadee8f1f162).
> > Caution
> > Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> > This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission
> > If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
> 
> can't make this as jar? as beta version? lol i totally dont understand what you wrote, ok thanks you resolved the issue but i dont see the jar

In the config.yml, change the `formatter` to `legacy`.

**Comment by Matt-MX** [comment]
I closed your previous post because I answered with the same thing...

https://github.com/Matt-MX/DisplayNameTags/issues/29
