### ISSUE TITLE
[Bug] Essentials Nicknames Not Working

### ISSUE THREAD

**Issue by PhoenixFireTea** [Matt-MX/DisplayNameTags#32]
I have been attempting to have Essentials nicknames appear in my nametags, but regardless of what I try it does not work. I am not sure if this is supported, but it seemed like it would / could be. Using essentials, I do /nick Coyotea &#900c3fCoyotea. If I have the formatter set to legacy, the hex color does not appear, and instead placeholders like %essentials_nickname% and %player_displayname% appear without color, as shown below. It appears in-game in chat and on TAB just fine, but not on the nametag itself.

```
defaults:
  # If not enabled then plugin simulates vanilla name tags
  enabled: true
  # How often should we refresh tags (in milliseconds)
  refresh-every: 1
  # Lines of text to display.
  text:
    - "%player_displayname%"
    - "%essentials_nickname%"
```

![2024-11-25_02 20 24](https://github.com/user-attachments/assets/005d9a32-3d98-4cad-9645-ce4576054447)

![2024-11-25_02 23 08](https://github.com/user-attachments/assets/0ba29df8-f2b4-4547-b0d5-f28b22d713f7)

![2024-11-25_02 24 06](https://github.com/user-attachments/assets/ae292397-e7af-46da-8dda-14680739dc7b)

If I do minimessage as the formatter, the entire nametag disappears and I get the error that "Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour."

```
[02:31:43 WARN]: Async task for NameTags v1.3-commit-ac52164 generated an exception
net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
	§x§9§0§0§c§3§fCoyotea§r
	  ^^
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[adventure-text-minimessage-4.17.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[adventure-text-minimessage-4.17.0.jar:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextFormatter.lambda$static$0(TextFormatter.java:15) ~[DisplayNameTags-1.3.jar:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextFormatter.format(TextFormatter.java:42) ~[DisplayNameTags-1.3.jar:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.convertToComponent(TextDisplayMetaConfiguration.java:183) ~[DisplayNameTags-1.3.jar:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.lambda$applyTextMeta$0(TextDisplayMetaConfiguration.java:27) ~[DisplayNameTags-1.3.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.TextDisplayMetaConfiguration.applyTextMeta(TextDisplayMetaConfiguration.java:35) ~[DisplayNameTags-1.3.jar:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:69) ~[DisplayNameTags-1.3.jar:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

![2024-11-25_02 31 30](https://github.com/user-attachments/assets/8ae73d0e-d98e-48c2-8655-b3457184bf86)

**Comment by Matt-MX** [comment]
In your config.yml change `formatter: minimessage` to `formatter: legacy`.

**Comment by Matt-MX** [comment]
I'll check this out tomorrow if I can get my laptop to get intellij working lmfao

**Comment by Matt-MX** [comment]
Can I please have your entire config please @PhoenixFireTea just for consistency?

**Comment by PhoenixFireTea** [comment]
Here is my NameTags Config:
https://paste.md-5.net/adoqadufeq.shell

Here is my Essentials Config:
https://paste.md-5.net/ekagududud.coffeescript

I have also found that it gives me the following error when I do /nametags-reload when I have my nick set as &#900c3fCoyotea :

```
[14:33:59 INFO]: Coyotea issued server command: /nick Coyotea &#900c3fCoyotea
[14:34:03 INFO]: Coyotea issued server command: /nametags-reload
[14:34:03 INFO]: Using LEGACY as text formatter.
[14:34:03 WARN]: Async task for NameTags v1.3-commit-ac52164 generated an exception
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:76) ~[DisplayNameTags-1.3.jar:?]
	at DisplayNameTags-1.3.jar/com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**Comment by Matt-MX** [comment]
@PhoenixFireTea Im not really able to access MC atm to test it, can you see if other legacy formatting things work?

e.g. `%luckperms_prefix%` or something for a rank with the meta prefix `&#010101Rank`

**Comment by PhoenixFireTea** [comment]
When I set my luckperms prefix to `prefix.100.&#C70039[Admin] `, and then display it in DisplayNameTags with `%luckperms_prefix%`, it does work with the legacy formatter.  The `%player_displayname%` and `%essentials_nickname%` don't get set to the right color and seemingly go to defaults.

![2024-11-28_17 32 07](https://github.com/user-attachments/assets/44c81060-ab8f-433f-8008-a3fe5317f662)

code in DisplayNameTags config:
```
  text:
    - "%luckperms_prefix%"
    - "%player_displayname%"
    - "%essentials_nickname%"
```

**Comment by Matt-MX** [comment]
This is strange behaviour, if you have tab installed could you run `/rab parse me %essentials_displayname%` please?

IIRC it gives the unformatted text as well which could be helpful to identify what %essentials_displayname% is returning exactly.

If not I can give it a look on monday (i should have my pc available)

**Comment by PhoenixFireTea** [comment]
I have tab installed. `%essentials_displayname%` isn't a placeholder, but I used `%essentials_nickname%` and `%player_displayname%`, as well as `%essentials_nickname_stripped%`. 

![image](https://github.com/user-attachments/assets/08434d51-19d7-4553-a325-2fbf55ea1365)
![image](https://github.com/user-attachments/assets/a6a37ee3-dfdf-4bd4-90b3-44e38663757d)
![image](https://github.com/user-attachments/assets/d18eb8ad-7ef2-4f47-8cdb-db687c36f8ac)




Here are some other photos for good measure:

![2024-11-29_21 58 19](https://github.com/user-attachments/assets/9f0b4f45-29fe-4180-b9ea-c48b648ddb15)

Code:
```
  text:
    - "%player_displayname%"
    - "%essentials_nickname%"
    - "%luckperms_prefix%"
    - "%essentials_nickname_stripped%"
    - "%player_list_name%"
```
![image](https://github.com/user-attachments/assets/1d30376d-1aa0-49d8-9afa-da87d1c0ae46)

![image](https://github.com/user-attachments/assets/68d048cc-d49b-47f6-8adc-e3759d4501a3)

![image](https://github.com/user-attachments/assets/878938c1-9c33-4e93-97a1-ba89c9b0352a)

![image](https://github.com/user-attachments/assets/7819edd7-9bd6-4635-894d-4da59e1eba08)

![image](https://github.com/user-attachments/assets/f7dee3e9-d2a5-45f6-94fd-44e9cbb2a591)

**Comment by Matt-MX** [comment]
Thanks so much I think I understand why it's not working.

My plug-in parses Legacy rgb codes in the format &#RRGGBB, not the old console one that essentials uses.

Not too sure on how to fix this via placeholders...

**Comment by PhoenixFireTea** [comment]
No problem. I think there is a way to convert it, something like:
```
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class ColorFormatter {

    //converts legacy hex format &x&9&0&0&c&3&f to modern hex format &#900c3f
    public static String convertLegacyHex(String input) {
        //regex to match the legacy hex format
        String legacyHexPattern = "&x(&[0-9a-fA-F]){6}";
        Pattern pattern = Pattern.compile(legacyHexPattern);
        Matcher matcher = pattern.matcher(input);

        StringBuffer result = new StringBuffer();
        while (matcher.find()) {
            String legacyHex = matcher.group();
            //extract hex digits from the legacy format
            String hexColor = legacyHex.replace("&x", "").replace("&", "");
            //replace with modern format
            String modernHex = "&#" + hexColor;
            matcher.appendReplacement(result, modernHex);
        }
        matcher.appendTail(result);

        return result.toString();
    }
```

**Comment by Matt-MX** [comment]
Awesome thanks, I've added that to the legacy formatter but havent tested it out. Here's the latest dev build if you could check it out! Thanks!

https://github.com/Matt-MX/DisplayNameTags/actions/runs/12101896275/job/33742318630

**Comment by PhoenixFireTea** [comment]
Unfortunately it didn't seem to work. It didn't give any errors and I was able to compile and run it just fine, so I think it might just need some more integration with the rest of the plugin. I'm not exactly a plugin developer either, so I might have did something wrong as well.

**Comment by Matt-MX** [comment]
Tested it on my machine and it's working now!

Also introduced `smart` formatter which attempts to format legacy -> minimessage so you can use both if needed, but I don't recommend its a bit messy and may produce unexpected results.

https://github.com/Matt-MX/DisplayNameTags/actions/runs/12106870655/job/33753107083

**Comment by PhoenixFireTea** [comment]
It works! Thank you so much for all your help!
