### ISSUE TITLE
[00:00:49 WARN]: [NameTags] Async task for NameTags v1.4-commit-1681401 generated an exception

### ISSUE THREAD

**Issue by TymonLC** [Matt-MX/DisplayNameTags#38]
https://prnt.sc/lxDX449mX6b8 sorry for picture i cant get logs

**Comment by TymonLC** [comment]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:07 WARN]: [NameTags] Async task for NameTags v1.3-commit-ac52164 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()'
        at com.mattmx.nametags.entity.NameTagEntity.isInvisible(NameTagEntity.java:53) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.NameTagEntity.updateVisibility(NameTagEntity.java:57) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:107) ~[DisplayNameTags-1.3.jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]

**Comment by Matt-MX** [comment]
Can you try and recreate this on 1.21

**Comment by TymonLC** [comment]
> Can you try and recreate this on 1.21

With packetevents 2.7.0 and displaynametags 1.4.0 no problems

**Comment by TymonLC** [comment]
> Can you try and recreate this on 1.21

[00:33:35 WARN]: [NameTags] Async task for NameTags v1.4-commit-1681401 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:76) ~[DisplayNameTags-1.4 (1).jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.4 (1).jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:33:35 WARN]: [NameTags] Async task for NameTags v1.4-commit-1681401 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:76) ~[DisplayNameTags-1.4 (1).jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.4 (1).jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:33:35 WARN]: [NameTags] Async task for NameTags v1.4-commit-1681401 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:76) ~[DisplayNameTags-1.4 (1).jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.4 (1).jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:33:35 WARN]: [NameTags] Async task for NameTags v1.4-commit-1681401 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:76) ~[DisplayNameTags-1.4 (1).jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.4 (1).jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:33:35 WARN]: [NameTags] Async task for NameTags v1.4-commit-1681401 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:76) ~[DisplayNameTags-1.4 (1).jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.4 (1).jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:33:35 WARN]: [NameTags] Async task for NameTags v1.4-commit-1681401 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1863) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.mattmx.nametags.config.ConfigDefaultsListener.lambda$registerDefaultRefreshListener$2(ConfigDefaultsListener.java:76) ~[DisplayNameTags-1.4 (1).jar:?]
        at com.mattmx.nametags.entity.trait.RefreshTrait.lambda$onEnable$0(RefreshTrait.java:41) ~[DisplayNameTags-1.4 (1).jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]


in 1.20.4 
DisplayNameTags-1.4 (1).jar
packetevents-spigot-2.7.0.jar

**Comment by TymonLC** [comment]
could you fix this? or provide steps for fix 
I won't update to 1.21 lobby

**Comment by Matt-MX** [comment]
I will fix the concurrent modification exception but I will not be adding compatibility for older versions. 1.20.4 should be okay it seems

**Comment by Matt-MX** [comment]
Fixed in the dev branch. The Concurrent modification error is only really cosmetic and doesn't actually cause the plugin to function unexpectedly in any way.

**Comment by TymonLC** [comment]
> Fixed in the dev branch. The Concurrent modification error is only really cosmetic and doesn't actually cause the plugin to function unexpectedly in any way.

send me link to dev version

**Comment by Matt-MX** [comment]
> > Fixed in the dev branch. The Concurrent modification error is only really cosmetic and doesn't actually cause the plugin to function unexpectedly in any way.
> 
> send me link to dev version

Will do in another post once I add relational nametags

**Comment by Matt-MX** [comment]
`see-self` is super buggy and I recommend not using it for the time being #23

**Comment by Matt-MX** [comment]
Please stop posting in issues I have closed, and reply to your other threads I am still waiting for your config.
