### ISSUE TITLE
[suggestion[ Yaml detector

### ISSUE THREAD

**Issue by TymonLC** [Matt-MX/DisplayNameTags#39]
I have suggestion to add simple yaml detector. I pasted my ready config and reloaded plugin and whaT? There is no nametags (i have show self true) no errrors in console and I checked this with yaml validator and he said me that i dont have some " after the end. So this is my suggestion: Add error when there is no " , when there is 2x more space than should be , could you please? 
https://prnt.sc/6EFO4ByaCfXW
https://prnt.sc/US7F2VEIpqhQ

**Comment by Matt-MX** [comment]
There should be errors in console when the plugin is reloaded.

**Comment by Matt-MX** [comment]
Tested this myself, errors are printed when there is an invalid config. There might be something else going wrong but I need the config to know.

```
[23:55:33 ERROR]: Cannot load plugins\NameTags\config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a quoted scalar
 in 'reader', line 13, column 7:
        - "<bold>%player_name%</bold><gold ... 
          ^
found unexpected end of stream
 in 'reader', line 30, column 1:
    
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:112) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:310) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:180) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at DisplayNameTags-1.4-1734306811298.jar/com.mattmx.nametags.NameTags.reloadConfig(NameTags.java:67) ~[DisplayNameTags-1.4-1734306811298.jar:?]
	at DisplayNameTags-1.4-1734306811298.jar/com.mattmx.nametags.NameTagsCommand.onCommand(NameTagsCommand.java:33) ~[DisplayNameTags-1.4-1734306811298.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1001) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:986) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a quoted scalar
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a quoted scalar

 in 'reader', line 13, column 7:
        - "<bold>%player_name%</bold><gold ... 
          ^
found unexpected end of stream
 in 'reader', line 30, column 1:
    
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarSpaces(ScannerImpl.java:1976) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1884) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1057) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1039) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:427) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntryValue.produce(ParserImpl.java:567) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntryKey.produce(ParserImpl.java:543) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceFirstEntry.produce(ParserImpl.java:530) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:272) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:105) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 16 more
[23:55:33 INFO]: [NameTags] Using MINI_MESSAGE as text formatter.
[23:55:33 INFO]: Reloaded!```

**Comment by TymonLC** [comment]
i didnt have " and didnt had this yaml errors idk why, can u test it ? remove one "

**Comment by Matt-MX** [comment]
> i didnt have " and didnt had this yaml errors idk why, can u test it ? remove one "

Bro I said I need your config on 3 seperate issues...
